apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx
  namespace: argocd
spec:
  destination:
    namespace: argocd-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-demo
    repoURL: https://github.com/mguay22/argocd-demo
    targetRevision: HEAD
