apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-concepts
  annotations:
    argocd-image-updater.argoproj.io/image-list: default=mguay22/nodejs-concepts:latest
    argocd-image-updater.argoproj.io/default.update-strategy: digest
  namespace: argocd
spec:
  destination:
    namespace: nodejs-concepts
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    targetRevision: main
    path: apps/nodejs-concepts
    repoURL: https://github.com/mguay22/argocd-demo
